/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto_3;

import java.awt.Color;
import java.awt.event.KeyEvent;

/**
 *
 * @author Heiner
 */
public class EditorTexto extends javax.swing.JDialog {

    private Archivo archivo;
    private Boolean saliendo;

    /**
     * Creates new form EditorTexto
     * @param parent
     * @param modal
     * @param archivo
     */
    public EditorTexto(java.awt.Frame parent, boolean modal, Archivo archivo) {
        super(parent, modal);
        initComponents();
        this.saliendo = false;
        this.archivo = archivo;
        this.setLocationRelativeTo(null);
        this.getContentPane().setBackground(Color.BLACK);
        lbInstrucciones.setForeground(Color.WHITE);
        lbTitulo.setForeground(Color.WHITE);
        lbMSGGuardar1.setForeground(Color.WHITE);
        lbMSGGuardar2.setForeground(Color.WHITE);
        lbNombreArchivo.setForeground(Color.WHITE);
        taTextoEditando.setBackground(Color.BLACK);
        taTextoEditando.setForeground(Color.WHITE);
        taTextoEditando.setText(archivo.textoArchivo);
        lbNombreArchivo.setText(archivo.nombre);
        lbMSGGuardar1.setVisible(false);
        lbMSGGuardar2.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        taTextoEditando = new javax.swing.JTextArea();
        lbTitulo = new javax.swing.JLabel();
        lbNombreArchivo = new javax.swing.JLabel();
        lbInstrucciones = new javax.swing.JLabel();
        lbMSGGuardar1 = new javax.swing.JLabel();
        lbMSGGuardar2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(374, 74));
        setUndecorated(true);
        setResizable(false);

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        taTextoEditando.setColumns(20);
        taTextoEditando.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        taTextoEditando.setRows(5);
        taTextoEditando.setCaretColor(java.awt.Color.white);
        taTextoEditando.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        taTextoEditando.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                taTextoEditandoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                taTextoEditandoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                taTextoEditandoKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(taTextoEditando);

        lbTitulo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lbTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTitulo.setText("COSMOS EDITOR");

        lbNombreArchivo.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        lbNombreArchivo.setText("Archivo: nombreArchivo");

        lbInstrucciones.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lbInstrucciones.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbInstrucciones.setText("Presione Ctrl + X para salir");

        lbMSGGuardar1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lbMSGGuardar1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbMSGGuardar1.setText("Presione S para guardar");

        lbMSGGuardar2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lbMSGGuardar2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbMSGGuardar2.setText("Otra tecla para descartar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(lbTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbNombreArchivo)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbInstrucciones, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbMSGGuardar1, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                            .addComponent(lbMSGGuardar2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(9, 9, 9)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(lbNombreArchivo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbInstrucciones, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbMSGGuardar1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbMSGGuardar2)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void taTextoEditandoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_taTextoEditandoKeyPressed
        if(saliendo){
            if(evt.getKeyCode() == KeyEvent.VK_S){
                archivo.textoArchivo = taTextoEditando.getText();
                archivo.guardar = true;
            }this.dispose();
        }else if(evt.isControlDown() && evt.getKeyCode() == KeyEvent.VK_X){
            saliendo = true;
            lbInstrucciones.setVisible(false);
            lbMSGGuardar1.setVisible(true);
            lbMSGGuardar2.setVisible(true);
        }
        
    }//GEN-LAST:event_taTextoEditandoKeyPressed

    private void taTextoEditandoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_taTextoEditandoKeyReleased
        
    }//GEN-LAST:event_taTextoEditandoKeyReleased

    private void taTextoEditandoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_taTextoEditandoKeyTyped
        
    }//GEN-LAST:event_taTextoEditandoKeyTyped

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbInstrucciones;
    private javax.swing.JLabel lbMSGGuardar1;
    private javax.swing.JLabel lbMSGGuardar2;
    private javax.swing.JLabel lbNombreArchivo;
    private javax.swing.JLabel lbTitulo;
    private javax.swing.JTextArea taTextoEditando;
    // End of variables declaration//GEN-END:variables
}
